env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
  no-console: 0,
  import/extensions: 0,
}
